from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin # Flask-Login için gerekli
from datetime import datetime, timedelta # Import datetime and timedelta
import uuid # For generating affiliate codes
import decimal # For commission amounts

# --- Association Table for User <-> AffiliateLink (Referral Tracking) ---
# !!! Temporarily removed definition as AffiliateLink model is missing !!!
# user_referrer = db.Table('user_referrer', db.metadata,
#     db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True),
#     db.Column('affiliate_link_id', db.Integer, db.ForeignKey('affiliate_link.id'), primary_key=True)
# )

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True, nullable=False)
    email = db.Column(db.String(120), index=True, unique=True, nullable=False)
    password_hash = db.Column(db.String(128))
    role = db.Column(db.String(20), index=True, nullable=False, default='user')
    telegram_accounts = db.relationship('TelegramAccount', backref='owner', lazy='dynamic', cascade="all, delete-orphan")
    
    # Command usage tracking fields
    command_usage_count = db.Column(db.Integer, nullable=False, default=0)
    last_usage_reset = db.Column(db.DateTime, nullable=True, default=None)
    
    # --- Affiliate System Fields ---
    affiliate_code = db.Column(db.String(10), unique=True, index=True, nullable=True)
    referred_by_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    
    # Points/Credits System
    credits = db.Column(db.Integer, default=0, nullable=False)
    # OwO Game Fields
    last_hunt_at = db.Column(db.DateTime, nullable=True)
    
    # Relationships for affiliate system
    # Users referred by this user
    referrals = db.relationship('User', backref=db.backref('referrer', remote_side='User.id'), lazy='dynamic') 
    # Earnings generated by this user as an affiliate
    affiliate_earnings = db.relationship('AffiliateEarning', foreign_keys='AffiliateEarning.affiliate_id', backref='affiliate', lazy='dynamic')
    # --- End Affiliate System Fields ---

    # Relationships
    notifications = db.relationship('Notification', 
                                 back_populates='user',  # Use back_populates
                                 lazy='dynamic', 
                                 cascade='all, delete-orphan')
    # Relationship to Python commands submitted by the user
    submitted_python_commands = db.relationship(
        'PythonCommand', 
        back_populates='submitter',  # Use back_populates
        lazy='dynamic', 
        foreign_keys='PythonCommand.submitted_by_user_id', 
        cascade='all, delete-orphan'
    )
    # Relationship to track who referred this user
    # Use the table object directly, now that it's defined above
    # !!! Temporarily commented out until AffiliateLink model is defined !!!
    # referred_by_link = db.relationship('AffiliateLink', secondary=user_referrer, back_populates='referred_users', uselist=False)
    # Relationship to the affiliate link this user owns (if any)
    # !!! Temporarily commented out until AffiliateLink model is defined !!!
    # affiliate_link = db.relationship('AffiliateLink', back_populates='user', uselist=False, foreign_keys='AffiliateLink.user_id', cascade='all, delete-orphan')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def is_admin(self):
        return self.role == 'admin'
        
    def is_premium(self):
        return self.role in ['admin', 'premium']
        
    def can_use_command(self, monthly_limit):
        """Checks if the user can use a command based on usage and resets if needed."""
        now = datetime.utcnow()
        # Reset check: if last reset is null or older than 30 days
        needs_reset = self.last_usage_reset is None or (now - self.last_usage_reset) > timedelta(days=30)
        
        if needs_reset:
            self.command_usage_count = 0
            self.last_usage_reset = now
            # Note: Need to commit this change in the calling code
            
        if self.is_admin() or self.is_premium():
            return True # Admins/Premium have no usage limits
        
        return self.command_usage_count < monthly_limit
        
    def increment_command_usage(self):
        """Increments the command usage count."""
        # Only increment if not admin/premium, although check is usually done before calling this
        if not self.is_admin() and not self.is_premium():
            # Ensure count is not None, default should handle this but good practice
            self.command_usage_count = (self.command_usage_count or 0) + 1
            # Note: Need to commit this change in the calling code

    def generate_affiliate_code(self):
        """Generates a unique affiliate code."""
        # Simple approach: USER + ID, ensure uniqueness
        potential_code = f"U{self.id}{uuid.uuid4().hex[:4].upper()}" # Add some randomness
        # Ensure it's unique (though collisions are highly unlikely with uuid)
        while User.query.filter_by(affiliate_code=potential_code).first():
             potential_code = f"U{self.id}{uuid.uuid4().hex[:4].upper()}"
        self.affiliate_code = potential_code
        # Note: Needs db.session.commit() later

    def __repr__(self):
        return f'<User {self.username} (ID: {self.id})>'

class TelegramAccount(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    phone_number = db.Column(db.String(20), unique=True, nullable=False)
    api_id = db.Column(db.Integer, nullable=False)
    api_hash = db.Column(db.String(64), nullable=False)
    session_string = db.Column(db.Text, nullable=True) # Telethon session string'i
    is_active = db.Column(db.Boolean, default=False)
    status = db.Column(db.String(50), default='pending_login') # e.g., pending_login, pending_code, active, error

    def __repr__(self):
        return f'<TelegramAccount {self.phone_number} for User {self.user_id}>'

class CustomCommand(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    account_id = db.Column(db.Integer, db.ForeignKey('telegram_account.id'), nullable=False, index=True)
    trigger = db.Column(db.String(100), nullable=False) # e.g., "!selam" or "sa"
    response = db.Column(db.Text, nullable=False) # The response text
    is_active = db.Column(db.Boolean, default=True, nullable=False)
    # Add more fields later if needed (e.g., description, exact_match, case_sensitive)

    # Define the relationship back to TelegramAccount
    account = db.relationship('TelegramAccount', backref=db.backref('custom_commands', lazy='dynamic', cascade='all, delete-orphan'))

    # Ensure trigger is unique per account
    __table_args__ = (db.UniqueConstraint('account_id', 'trigger', name='uq_account_trigger'),)

    def __repr__(self):
        return f'<CustomCommand {self.trigger} for Account {self.account_id}>'

# --- Notification Model --- 
class Notification(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False, index=True) # Recipient
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    name = db.Column(db.String(128), nullable=False) # Short identifier (e.g., 'new_user_registered')
    payload_json = db.Column(db.Text) # Optional JSON data for the notification message
    is_read = db.Column(db.Boolean, default=False, nullable=False)

    # Relationship to User (optional, for easy access to recipient)
    user = db.relationship('User', 
                         back_populates='notifications' # Use back_populates
                         )

    def get_message(self):
        """Generates the display message based on the notification name and payload."""
        from flask_babel import _
        import json
        
        try:
            data = json.loads(self.payload_json) if self.payload_json else {}
        except json.JSONDecodeError:
            data = {}
            print(f"!!! Could not decode JSON payload for notification {self.id}")

        if self.name == 'new_user_registered':
            username = data.get('username', _('Unknown User'))
            return _('New user registered: %(username)s', username=username)
            
        elif self.name == 'limit_reached':
             limit_type = data.get('limit_type', 'command') # e.g., 'command', 'bot'
             limit_value = data.get('limit_value', 0)
             if limit_type == 'bot':
                  return _('You have reached your bot account limit (%(limit)s).', limit=limit_value)
             else: # Default to command limit
                  return _('You have reached your monthly command usage limit (%(limit)s).', limit=limit_value)
                  
        elif self.name == 'bot_error':
            error_type = data.get('error_type', 'UnknownError')
            phone = data.get('phone', '')
            message = data.get('message', '')
            seconds = data.get('seconds')
            
            if error_type == 'FloodWaitError':
                 return _('Login for %(phone)s failed (Too many attempts). Please try again in %(seconds)s seconds.', phone=phone, seconds=seconds)
            elif error_type == 'SendCodeError':
                 return _('Failed to send verification code to %(phone)s. Error: %(message)s', phone=phone, message=message)
            elif error_type == 'SessionRetrievalError':
                  return _('Login for %(phone)s succeeded but failed to get session key. Bot cannot start.', phone=phone)
            elif error_type == 'PhoneCodeInvalidError':
                  return _('Invalid verification code entered for %(phone)s.', phone=phone)
            elif error_type == 'SessionPasswordNeededError':
                   return _('Login for %(phone)s requires 2FA password (not supported).', phone=phone)
            elif error_type == 'CodeVerificationError':
                 return _('Code verification failed for %(phone)s. Error: %(message)s', phone=phone, message=message)
            elif error_type == 'StartRunnerError':
                 return _('Failed to start the bot for %(phone)s. Error: %(message)s', phone=phone, message=message)
            else:
                 return _('An unknown bot error occurred for %(phone)s.', phone=phone)
                 
        elif self.name == 'bot_warning': # Handling the warning type
            error_type = data.get('error_type', 'UnknownWarning')
            phone = data.get('phone', '')
            message = data.get('message', '')
            if error_type == 'DeleteSessionError':
                return _('Warning: Bot account %(phone)s deleted, but session files could not be removed. Error: %(message)s', phone=phone, message=message)
            else:
                 return _('A bot warning occurred for %(phone)s.', phone=phone)

        # --- Add other notification types here --- 
                 
        return _('You have a new notification.') # Default generic message

    def __repr__(self):
        return f'<Notification {self.name} for User {self.user_id}>' 

# --- Affiliate Earning Model --- 
class AffiliateEarning(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    affiliate_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False, index=True) # Who earned the commission
    referred_user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False, index=True) # Which referred user triggered it
    amount = db.Column(db.Numeric(10, 2), nullable=False) # Commission amount (e.g., 5.00)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    status = db.Column(db.String(20), nullable=False, default='pending', index=True) # e.g., 'pending', 'paid', 'cancelled'
    notes = db.Column(db.String(255), nullable=True) # Optional notes (e.g., reason for cancellation)

    # Relationships (optional but helpful)
    referred_user = db.relationship('User', foreign_keys=[referred_user_id]) # Removed backref to avoid confusion with User.referrals

    def __repr__(self):
        return f'<AffiliateEarning {self.amount} for {self.affiliate_id} from {self.referred_user_id}>' 

# --- Python Command Model --- 
class PythonCommand(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    account_id = db.Column(db.Integer, db.ForeignKey('telegram_account.id'), nullable=False, index=True)
    submitted_by_user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False, index=True)
    
    trigger = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(255), nullable=True)
    code_body = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(20), nullable=False, default='pending', index=True)
    review_notes = db.Column(db.Text, nullable=True)
    
    # --- Market Fields ---
    is_public = db.Column(db.Boolean, default=False, nullable=False, index=True)
    original_command_id = db.Column(db.Integer, db.ForeignKey('python_command.id'), nullable=True)
    # --- End Market Fields ---

    created_at = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, index=True, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    account = db.relationship('TelegramAccount', backref=db.backref('python_commands', lazy='dynamic', cascade='all, delete-orphan'))
    submitter = db.relationship(
        'User', 
        foreign_keys=[submitted_by_user_id], 
        back_populates='submitted_python_commands'  # Use back_populates
    )
    original_command = db.relationship('PythonCommand', remote_side=[id], foreign_keys=[original_command_id])
    # Relationship to categories (Many-to-Many)
    categories = db.relationship('CommandCategory', secondary='python_command_category', back_populates='commands', lazy='dynamic')

    # Ensure trigger is unique per account
    __table_args__ = (db.UniqueConstraint('account_id', 'trigger', name='uq_pycommand_account_trigger'),)

    def __repr__(self):
        return f'<PythonCommand {self.trigger} for Account {self.account_id} ({self.status})>' 

# --- Command Category Model --- 
class CommandCategory(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    slug = db.Column(db.String(80), unique=True, nullable=False, index=True)
    description = db.Column(db.String(255), nullable=True)

    # Relationship back to commands (Many-to-Many)
    commands = db.relationship('PythonCommand', secondary='python_command_category', back_populates='categories', lazy='dynamic')

    def __init__(self, name, description=None):
        self.name = name
        self.slug = name.lower().replace(' ', '-').replace('_', '-') # Basic slug generation
        # Ensure slug uniqueness (might need more robust generation)
        # TODO: Add uniqueness check/generation for slug
        self.description = description
        
    def __repr__(self):
        return f'<CommandCategory {self.name}>'

# --- Association Table for PythonCommand <-> CommandCategory --- 
python_command_category = db.Table('python_command_category', db.metadata,
    db.Column('python_command_id', db.Integer, db.ForeignKey('python_command.id'), primary_key=True),
    db.Column('category_id', db.Integer, db.ForeignKey('command_category.id'), primary_key=True)
)

# --- Command Rating/Review Model --- 
class CommandRating(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    python_command_id = db.Column(db.Integer, db.ForeignKey('python_command.id'), nullable=False, index=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False, index=True)
    rating = db.Column(db.Integer, nullable=False) # e.g., 1 to 5 stars
    comment = db.Column(db.Text, nullable=True)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    # Relationships
    command = db.relationship('PythonCommand', backref=db.backref('ratings', lazy='dynamic', cascade='all, delete-orphan'))
    user = db.relationship('User', backref=db.backref('ratings_given', lazy='dynamic'))

    # Constraint: A user can rate a specific command only once
    __table_args__ = (db.UniqueConstraint('python_command_id', 'user_id', name='uq_command_user_rating'),
                      # Check constraint for rating value (1-5)
                      db.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range')) 

    def __repr__(self):
        return f'<CommandRating {self.rating} for Command {self.python_command_id} by User {self.user_id}>'

# --- OwO Game Models --- 

# Animal Species (The blueprint for each animal)
class AnimalSpecies(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    emoji = db.Column(db.String(10), nullable=False)
    rarity = db.Column(db.String(20), nullable=False, index=True) # e.g., Common, Rare, Epic
    base_value = db.Column(db.Integer, nullable=False, default=1) # Value when selling
    # Optional: description, habitat, etc.
    
    # Relationship to user inventories
    owned_by_users = db.relationship('UserAnimal', back_populates='species', cascade='all, delete-orphan')

    def __repr__(self):
        return f'<AnimalSpecies {self.name} ({self.rarity})>'

# User's Animal Inventory (Tracks count of each species per user)
class UserAnimal(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False, index=True)
    animal_species_id = db.Column(db.Integer, db.ForeignKey('animal_species.id'), nullable=False, index=True)
    quantity = db.Column(db.Integer, nullable=False, default=1)
    
    # Timestamps can be useful
    first_caught_at = db.Column(db.DateTime, default=datetime.utcnow)
    last_updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    user = db.relationship('User', backref=db.backref('animal_inventory', lazy='dynamic'))
    species = db.relationship('AnimalSpecies', back_populates='owned_by_users')

    # Constraint: A user should only have one row per animal species
    __table_args__ = (db.UniqueConstraint('user_id', 'animal_species_id', name='uq_user_animal_species'),)

    def __repr__(self):
        return f'<UserAnimal User: {self.user_id}, Species: {self.animal_species_id}, Qty: {self.quantity}>'

# --- End OwO Game Models --- 

# --- Affiliate Link Model ---
# ... rest of the file ... 