"""add owo game models

Revision ID: 20d20077ea0f
Revises: 7d5216ad11b1
Create Date: 2025-04-26 19:09:58.632081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d20077ea0f'
down_revision = '7d5216ad11b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('base_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('animal_species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_species_rarity'), ['rarity'], unique=False)

    op.create_table('user_animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_species_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('first_caught_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_species_id'], ['animal_species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'animal_species_id', name='uq_user_animal_species')
    )
    with op.batch_alter_table('user_animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_animal_animal_species_id'), ['animal_species_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_animal_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_animal_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_animal_animal_species_id'))

    op.drop_table('user_animal')
    with op.batch_alter_table('animal_species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_species_rarity'))

    op.drop_table('animal_species')
    # ### end Alembic commands ###
