"""initial migration

Revision ID: 376ee1353a19
Revises: 
Create Date: 2025-04-26 18:54:59.757762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376ee1353a19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('command_usage_count', sa.Integer(), nullable=False),
    sa.Column('last_usage_reset', sa.DateTime(), nullable=True),
    sa.Column('affiliate_code', sa.String(length=10), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_affiliate_code'), ['affiliate_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('affiliate_earning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_earning', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_earning_affiliate_id'), ['affiliate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_earning_referred_user_id'), ['referred_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_earning_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_earning_timestamp'), ['timestamp'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('telegram_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(length=64), nullable=False),
    sa.Column('session_string', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('custom_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trigger', name='uq_account_trigger')
    )
    with op.batch_alter_table('custom_command', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_command_account_id'), ['account_id'], unique=False)

    op.create_table('python_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('code_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('original_command_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_account.id'], ),
    sa.ForeignKeyConstraint(['original_command_id'], ['python_command.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trigger', name='uq_pycommand_account_trigger')
    )
    with op.batch_alter_table('python_command', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_python_command_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_python_command_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_python_command_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_python_command_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_python_command_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_python_command_updated_at'), ['updated_at'], unique=False)

    op.create_table('command_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('python_command_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['python_command_id'], ['python_command.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('python_command_id', 'user_id', name='uq_command_user_rating')
    )
    with op.batch_alter_table('command_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_rating_python_command_id'), ['python_command_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_rating_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_command_rating_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_rating_user_id'))
        batch_op.drop_index(batch_op.f('ix_command_rating_timestamp'))
        batch_op.drop_index(batch_op.f('ix_command_rating_python_command_id'))

    op.drop_table('command_rating')
    with op.batch_alter_table('python_command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_python_command_updated_at'))
        batch_op.drop_index(batch_op.f('ix_python_command_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_python_command_status'))
        batch_op.drop_index(batch_op.f('ix_python_command_is_public'))
        batch_op.drop_index(batch_op.f('ix_python_command_created_at'))
        batch_op.drop_index(batch_op.f('ix_python_command_account_id'))

    op.drop_table('python_command')
    with op.batch_alter_table('custom_command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_command_account_id'))

    op.drop_table('custom_command')
    op.drop_table('telegram_account')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))

    op.drop_table('notification')
    with op.batch_alter_table('affiliate_earning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_earning_timestamp'))
        batch_op.drop_index(batch_op.f('ix_affiliate_earning_status'))
        batch_op.drop_index(batch_op.f('ix_affiliate_earning_referred_user_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_earning_affiliate_id'))

    op.drop_table('affiliate_earning')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_affiliate_code'))

    op.drop_table('user')
    # ### end Alembic commands ###
