"""add command category model and relationship

Revision ID: 7d5216ad11b1
Revises: 376ee1353a19
Create Date: 2025-04-26 19:01:12.729737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5216ad11b1'
down_revision = '376ee1353a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('command_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_category_slug'), ['slug'], unique=True)

    op.create_table('python_command_category',
    sa.Column('python_command_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['command_category.id'], ),
    sa.ForeignKeyConstraint(['python_command_id'], ['python_command.id'], ),
    sa.PrimaryKeyConstraint('python_command_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('python_command_category')
    with op.batch_alter_table('command_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_category_slug'))

    op.drop_table('command_category')
    # ### end Alembic commands ###
