"""Add price column to PythonCommand again

Revision ID: 84f728e99ecc
Revises: 26c1ae78c64b
Create Date: 2025-04-26 23:37:13.534210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f728e99ecc'
down_revision = '26c1ae78c64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('python_command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_python_command_price'), ['price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('python_command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_python_command_price'))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
