"""add last_hunt_at to user

Revision ID: 97bcfd15d8c5
Revises: 20d20077ea0f
Create Date: 2025-04-26 19:13:14.759446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bcfd15d8c5'
down_revision = '20d20077ea0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_hunt_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_hunt_at')

    # ### end Alembic commands ###
