"""Add credits_earned to User model

Revision ID: fbfea3f1ce7a
Revises: 84f728e99ecc
Create Date: 2025-04-27 00:12:36.821123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfea3f1ce7a'
down_revision = '84f728e99ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_earned', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credits_earned')

    # ### end Alembic commands ###
